Welcome To Numpy Tutorial

In [1]:
import numpy as np

In [2]:

print("hello world")

hello world


In [3]:
import sklearn

In [4]:
i=45

In [5]:
print(7)

7


In [6]:
i

45

In [7]:
myarr = np.array([[3,6,37,7]], np.int64)

In [8]:
myarr[0,1]

np.int64(6)

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr


array([[ 3,  6, 37,  7]])

In [12]:
myarr[0,2]=45

In [13]:
myarr

array([[ 3,  6, 45,  7]])

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
linspace =np.linspace(1,5,12)

In [21]:
linspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
lspace=np.linspace(1,10,5)

In [23]:
lspace


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921822e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.24611402e-306, 1.33512173e-306,
        1.11261570e-306, 6.89804133e-307, 1.20161797e-306]])

In [26]:
emp_like =np.empty_like(lspace)

In [27]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
arr = np.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr = arr.ravel()

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

In [37]:
x =[[1,2,3],[4,5,6],[7,1,0]]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [42]:
ar.T   # it will transpose the matrix mean convert the row into column and column into row

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes

72

In [48]:
one = np.array([1,3,4,56,43,2])

In [49]:
one.argmax()

np.int64(3)

In [50]:
one.argmin()

np.int64(0)

In [51]:
one.argsort()

array([0, 5, 1, 2, 4, 3])

In [52]:
one.dtype

dtype('int64')

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

ar.srgmin()

In [54]:
ar.argmin()

np.int64(8)

In [55]:
ar.argmax(axis=0)

array([2, 1, 1])

In [58]:
ar.argmax()

np.int64(6)

In [59]:
ar.argmax(axis=1)

array([2, 2, 0])

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [61]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [62]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [70]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [71]:
ar2 = [[4,1,3],
       [5,2,1],
       [3,7,1,]]

In [72]:
ar3 = ar + ar2

In [73]:
ar3

array([[ 5,  3,  6],
       [ 9,  7,  7],
       [10,  8,  1]])

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
ar4= ar * ar2

In [85]:
ar4

array([[ 4,  2,  9],
       [20, 10,  6],
       [21,  7,  0]])

In [76]:
ar.min()

np.int64(0)

In [78]:
ar.sum()

np.int64(29)

In [79]:
ar.max()

np.int64(7)

In [82]:
np.sqrt(ar3)

array([[2.23606798, 1.73205081, 2.44948974],
       [3.        , 2.64575131, 2.64575131],
       [3.16227766, 2.82842712, 1.        ]])

In [92]:
np.where(ar4>19)

(array([1, 2]), array([0, 0]))

In [114]:
arrr =np.array( [[2,3,4],
        [9,2,5],
        [7,0,6]])

In [115]:
arrr 

array([[2, 3, 4],
       [9, 2, 5],
       [7, 0, 6]])

In [119]:
arrr2 =np.array([[2,3,4],
        [6,3,2],
        [2,6,1]])

In [120]:
arrr2

array([[2, 3, 4],
       [6, 3, 2],
       [2, 6, 1]])

In [121]:
arrr2.dtype

dtype('int64')

In [122]:
arrr2.reshape((9,1))

array([[2],
       [3],
       [4],
       [6],
       [3],
       [2],
       [2],
       [6],
       [1]])

In [124]:
arrr2.max()

np.int64(6)

In [125]:
arrr2.ravel()

array([2, 3, 4, 6, 3, 2, 2, 6, 1])

In [127]:
np.where(arrr2<2)

(array([2]), array([2]))

In [130]:
arrr2

array([[2, 3, 4],
       [6, 3, 2],
       [2, 6, 1]])

In [128]:
np.where(arrr2==6)

(array([1, 2]), array([0, 1]))

In [132]:
np.count_nonzero(arrr2)

9

In [140]:
np.nonzero(arrr2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [141]:
arrr2[1,0] = 0

In [142]:
np.nonzero(arrr2)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 1, 2, 0, 1, 2]))